### ISSUE TITLE
How to download and install the HANA Eclipse plugin

### ISSUE THREAD

**Issue by Balkarann** [SAPDocuments/How-Tos#128]
Starting from the step that says "Press Enter to display the available features.", more pictures should be provided after each step to help make it easier for users to know where to click to do what the step tells them to do. 

Before the first step 2, there should be a step telling the user to click on the "Add" button after clicking on "Help > Install New Software" and then the user should be told where to put the link provided in the current first step 2.

Step 6 should say "Change perspective to SAP HANA Administrative Console by clicking on Window > Perspective > SAP HANA Administrative Console". Also if it does not show "SAP HANA Administrative Console" after you click on "Window > Perspective", then you should click on Window > Perspective > Other... > SAP HANA Administrative Console

Step 7 should have an image should where to add a system from since someone who has never worked with eclipse may not know where to add a system from.

**Comment by JCurrie27** [comment]
Thanks for your feedback. We are improving the tutorials and will take your comments into consideration when making the updates.
