### ISSUE TITLE
How to prepare HANA, express edition environment for tutorials

### ISSUE THREAD

**Issue by Trivenn** [SAPDocuments/How-Tos#132]
I have replaced passwords here, but I am sure password that i have entered is correct.
I have issues in STEP 1.
hxeadm@hana-experiments-trivenn-vm:/usr/sap/HXE/HDB90> hdbsql i 90 n localhost:39015 u SYSTEM p Hana@123  "CREATE USER WORKSHOP_01 PASSWORD Hana@123 NO FORCE_FIRST_PASSW
ORD_CHANGE SET PARAMETER XS_RC_XS_CONTROLLER_USER = 'XS_CONTROLLER_USER' , XS_RC_DEVX_DEVELOPER = 'DEVX_DEVELOPER', XS_RC_XS_AUTHORIZATION_ADMIN = 'XS_AUTHORIZATION_ADMI
N'"
Username: SYSTEM
Password: 
* -10709: Connection failed (RTE:[89006] System call 'connect' failed, rc=111:Connection refused (localhost:30015))
hxeadm@hana-experiments-trivenn-vm:/usr/sap/HXE/HDB90>

**Comment by Lsubatin** [comment]
Hi Trivenn, the -d parameter for the database seems to be missing, Additionally, try with port 39013 if the instance number is 90 (the error message says 30015 but your parameter 39015).
