### ISSUE TITLE
How to connect to SAP HANA using Data Provider for Microsoft .NET

### ISSUE THREAD

**Issue by wurst0815** [SAPDocuments/How-Tos#138]
Hi, 

how does the connection string have to look like when trying to connect to a SAP Hana Trial Instance in the SAP Cloud?

Thanks,
Oliver

**Comment by JCurrie27** [comment]
Closing old issue. Not HANA express.

**Comment by JCurrie27** [comment]
Reassigning to Chris.

**Comment by JCurrie27** [comment]
Thanks for your feedback. We are improving the tutorials and will take your comments into consideration when making the updates.

**Comment by wurst0815** [comment]
Thanks, but that doesn't help me right now :-/
