### ISSUE TITLE
Feedback on Tutorial: SAP HANA, express edition Troubleshooting

### ISSUE THREAD

**Issue by SAPSuper** [SAPDocuments/How-Tos#15]
I guess the only issue with this is that in 60 days you owe Suse $2000-$4000 in subscription fees or .. start over to get a new freekey. 

I've tried updating from OpenSuse 12.1 repositories but Suse for SAP seems to be several generations ahead of Open and so nearly every update wants to downport critical versions of libs (like ssl you indicated here). 

Suggestions welcome...

**Comment by rleibbrandt** [comment]
Hello SAPSuper

Thank you for bringing this to our attention.    We're assuming that you already have a subscription for SLES, which we should probably document.     

If you don't want to go down that route - why not install OpenSuse?    SAP HANA, express edition is community supported, so there's no "formal" certification required.    

R
