### ISSUE TITLE
How to prepare HANA, express edition environment for tutorials

### ISSUE THREAD

**Issue by flinn2112** [SAPDocuments/How-Tos#158]
xs login -u xsa_admin -p <password>
yields in command not found:
If 'xs' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf xs

You should provide a suitable command substitute.

**Comment by Lsubatin** [comment]
Either you do not have xs installed (that is, you have a server-only version) or you have not done sudo su -hxeadm previously.  I'll review the tutorial to make this more clear though. Thanks for the feedback.
