### ISSUE TITLE
Troubleshooting // Step 6

### ISSUE THREAD

**Issue by ptiesat** [SAPDocuments/How-Tos#161]
I received that error due to the fact , that I loaded up the zip-archive mentioned in that hint. Error-Message in log-file was required Parameter appArchiveID not defined. 
Anyway doing again the steps will help , but zip - Archive XSACUI5FESV344_10.zip has been placed in <installation-path>/HANA_EXPRESS_20/DATA_UNITS/XSA_CONTENTS_10 and not in <installation-path>/HANA_EXPRESS_20/DATA_UNITS/HANA_COCKPIT_20...

**Comment by aplata-sap** [comment]
Issue is no longer relevant with SP02. Removing step.

**Comment by JCurrie27** [comment]
The how-to has been updated - closing this issue.
