### ISSUE TITLE
How to setup the SAP Vora developer edition in SAP CAL

### ISSUE THREAD

**Issue by KevinSmall** [SAPDocuments/How-Tos#166]
When I tried to use size xLarge and IOPS I got instance terminated:

Your virtual machine SAP VORA was unexpectedly terminated. Reason : Client.InvalidParameterCombination:Client.InvalidParameterCombination: Could not create volume with size 20GiB and iops 80 from snapshot 'snap-0cbdc68e516516cbf'.

**Comment by Sygyzmundovych** [comment]
Hi Kevin. Sorry for late response. Do you still have this issue?

**Comment by KevinSmall** [comment]
Hi Vitaliy,


I got around it ok by choosing a different size, just wanted to point it out for future readers of the instructions.


Kevin.

________________________________

**Comment by Sygyzmundovych** [comment]
There is no an option in CAL to create Vora 1.3 with IOPS. Could you please check you see that option? Much appreciated.

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
