### ISSUE TITLE
How to download and install the HANA Eclipse plugin

### ISSUE THREAD

**Issue by juankb1024** [SAPDocuments/How-Tos#167]
I was following the Eclipse Tutorial https://www.sap.com/developer/how-tos/2016/09/hxe-howto-eclipse.html but once installed, I couldn't connect to the VM.

"Cannot access system on host 'hxehost'"

After some time in google, I found out that since HXE 2.0, the default instance is not '00' but '90'

https://answers.sap.com/questions/112073/hana-express-edition-can-not-connect-with-system-u.html

You could mention in the tutorial which instance to use in each supported version.

Cheers!

**Comment by Lsubatin** [comment]
That was reviewed. Thanks for the feedback.
