### ISSUE TITLE
How to download and install the HANA Eclipse plugin

### ISSUE THREAD

**Issue by condamoor-sap** [SAPDocuments/How-Tos#169]
Hi
I am using Hana Exp 2.0, sp1..am tying to access it through Eclipse.
The default port that Hana plugin uses to connect to the SystemDB is 39015, whereas in sp1, I believe the port is 39013. How do I change the port number when I am going through the Add System process? I even downloaded the latest Hana plugin..but it still uses 39015 and not 39013.

Any suggestions?

Thanks
-ravi

**Comment by Lsubatin** [comment]
Hi, Ravi. I believe that by internal communications we had via email that you have tackled this, you do not need to change anything in Eclipse for the ports, it determines it automatically.

**Comment by condamoor-sap** [comment]
Yes…Thanks
