### ISSUE TITLE
How to Install SAP HANA 2.0, express edition Clients

### ISSUE THREAD

**Issue by StingyJack** [SAPDocuments/How-Tos#175]
A link to the actual clients is missing.

**Comment by JCurrie27** [comment]
Please see "Step 1: Download the Clients" in this tutorial. 
That step has links to the download page, and download instructions.

**Comment by JCurrie27** [comment]
Closing issue.

**Comment by StingyJack** [comment]
Which tutorial, specifically?

**Comment by JCurrie27** [comment]
Hi - I'm assuming you're looking for a link to the client download package. If you go to this tutorial: 

https://www.sap.com/developer/how-tos/2016/12/hxe-ua-howto-installing-clients.html

scroll down to **Step 1: Download the Clients** and expand that node. 
You should see information on downloading the Clients package using the Download Manager, and extracting it.

The URL to the XS CLI client is in "Step 3 (Windows/Linux): Install the SAP HANA HDB Client"; connection info for the HDB CLI client is in step "Post-Installation Info: SAP HANA HDB Client".

If this isn't the information you're looking for, please let me know and we'll help you locate it.

**Comment by StingyJack** [comment]
Yes, thanks!
