### ISSUE TITLE
How to download and install the HANA Eclipse plugin

### ISSUE THREAD

**Issue by sulthan1** [SAPDocuments/How-Tos#176]
I am not able to add a system in the HANA studio by following your tutorial. Can you help me? May be my userid and password were incorrect or the IP address.

**Comment by sulthan1** [comment]
[error test.docx](https://github.com/SAPDocuments/How-Tos/files/1006131/error.test.docx)

**Comment by Lsubatin** [comment]
Hi, it's probably late and this kind of question belongs in the Q&A where this is also addressed. The instance number should be 90 if you are using the Google launcher version.
