### ISSUE TITLE
Feedback on Tutorial: How to prepare HANA, express edition environment for tutorials

### ISSUE THREAD

**Issue by grahamrobbo** [SAPDocuments/How-Tos#19]
Accounts XSA_DEV & XSA_SHINE get deactivated due to password expiry. This means you are unable to change the default passwords as documented in the "Test XSC, XSA & WebIDE" section of the getting started document until you reactivate the users.

**Comment by carlsoane** [comment]
Hello Graham:

This problem has been corrected in the most recent release of HXE. In the meantime, you can change the password using the system user. Note that after changing the password as system you will still be required to change the password again after the first login as these users. 

hdbsql -u system -p (your password) -d SystemDB "alter user xsa_dev password (new password)

Carl
