### ISSUE TITLE
Create a Fiori for iOS app in 45 minutes

### ISSUE THREAD

**Issue by Amster2017** [SAPDocuments/How-Tos#206]
The backbone ODATA service seems not to work, it used to work before, I tested the URL also directly with a browser.

KR,

Steffen

**Comment by qualiture** [comment]
Hi @Amster2017,

My sincere apologies for the late reply. The service may have suffered from a small outage, but should be running -- I checked today

**Comment by qualiture** [comment]
Hi @Amster2017 

There is again a small outage (see related issue #223) -- I'll update once resolved

**Comment by qualiture** [comment]
Issue has been resolved
