### ISSUE TITLE
Tutorial Page hxe-db-deploy.md Issue. PROD

### ISSUE THREAD

**Issue by SAPDocs** [SAPDocuments/How-Tos#216]
Tutorial issue found: [https://github.com/SAPDocuments/How-Tos/blob/master/tutorials/2017/07/hxe-db-deploy/hxe-db-deploy.md](https://github.com/SAPDocuments/How-Tos/blob/master/tutorials/2017/07/hxe-db-deploy/hxe-db-deploy.md) contains invalid primary tag.
Your tutorial was not created. Please double-check primary tag property.

Each tutorial md-file shall have primary tag provided above. Example:
\-\-\-
title: Text Bundles within Node.js SAP HANA applications
description: Working with text bundles in Node.js
primary_tag: products>sap\-hana
tags: [ tutorial>intermediate\, products>sap\-hana\, products>sap\-hana\-\-express\-edition ]
\-\-\-

 Affected server: PROD

**Comment by akula86** [comment]
added tag: https://github.com/SAPDocuments/How-Tos/commit/91cd1c70f7376180a7d375734c192a07a505d282
