### ISSUE TITLE
How to setup the SAP Vora developer edition virtual machine

### ISSUE THREAD

**Issue by Suddybuddy** [SAPDocuments/How-Tos#224]
Thanks for the useful tutorial.
With regards to Step-6, what do I do if I see my Vora services in "inactive dead" statuses?
Thanks
![screenshot](https://user-images.githubusercontent.com/31724440/30151350-b15ab1e4-93cc-11e7-911f-60f1e17987ad.JPG)

**Comment by Sygyzmundovych** [comment]
This is usually happens when there is no enough memory available. What amount of RAM do you have assigned to your VM and what is the total on your computer?

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
