### ISSUE TITLE
SAP HANA 2.0, express edition Troubleshooting

### ISSUE THREAD

**Issue by pasedlar** [SAPDocuments/How-Tos#226]
Hi,

I am attempting to install HXE v2 sps2.  I have a Windows 7 machine with VMWare Workstation.  I have installed HXE v1 in the past with this Windows machine.

I am following the installation guide (https://www.sap.com/developer/tutorials/hxe-ua-getting-started-vm.html).  Everything seems good so far when checking what is running (xs apps | grep webide etc.).  I have checked the IP (/sbin/ifconfig) multiple times and have made sure my hxehost entry in my host file is correct.  When I test the XSEngine, it displays fine (successfully).  When I check the web ide it shows it is running, but when I try and access it from my Windows browser (chrome and ie), I get a connection reset message (error).  I decided to continue and install the SAP Enterprise Architecture Designer, and the install appeared to be successful.  I did a xs apps | grep eadesigner and everything matched the install instructions.  It showed eadesigner was at:  hxehost:51028 but again when I try and access it from a Windows browser I get a connection reset error message.

I have an "out of the box" Windows 7 install, and VMWare Workstation install with no added proxy, firewall or anything else.  It seems like something is blocking ports at 510**, my guess is it is somewhere on the VMWare side, but I am not sure where this blockage might be?

![hxe_2_eadesigner](https://user-images.githubusercontent.com/14805074/30915663-7cbcae9e-a365-11e7-8649-acc203226dcc.jpeg)

![hxe_eadesigner_error](https://user-images.githubusercontent.com/14805074/30915678-8892698e-a365-11e7-86ac-4ce6b77b00cb.jpeg)

Help!

Thanks.

**Comment by JCurrie27** [comment]
Hi pasedlar - do you still have this issue with the latest release of hxexsa.ova?

**Comment by pasedlar** [comment]
Hi John!

Thanks for getting back to me.  I have the latest HXE 2.0 Virtual
Machine install up and working.  This laptop has 32gb of memory.  I decided
to buy a new Dell Precision laptop with 64gb of memory.  Yesterday I
created a Virtual Machine (with 38gb of allocated memory) and installed
Ubuntu 16.04 (Linux) in this Virtual machine.  I know the binary install of
HXE is not officially supported on Ubuntu, but I have seen blogs where
people supposedly have it running in Ubuntu (Linux), so I am working on
this now.  My goal with this binary install is to fully utilize all 32gb
for HXE.

If you have any good references for the binary install on Ubuntu please let
me know.  My first attempt failed.  :/

Thanks again

**Comment by JCurrie27** [comment]
Hi pasedlar. Great to hear that you're making progress with that powerful machine. Since Ubuntu is not officially supported, I don't have any official documentation on it. However, I'll check my contacts and the community and will get back to you if I find any information on binary install on Ubuntu. In the meantime, I'll close this issue.
