### ISSUE TITLE
How to run SAP Vora on Amazon Web Services

### ISSUE THREAD

**Issue by jpvelezv** [SAPDocuments/How-Tos#228]
Good morning,

I have a suggestion. I followed all the steps of this tutorial a month ago and it mention in step 1 that it is a free developer edition, but in step 3 when they ask to select the instance type m4.2xlarge, this is not free, 
 please make a warning to users. I had the bad experience that I would be charged a few instances in AWS, so please highlight or warn people that it will generate a charge to credit card.

I expect an update of the tutorial with this warning. Thank you.

**Comment by Sygyzmundovych** [comment]
Hi Juan. Thank you for the comment. I'll let the original author to make it more clear in the next version of the tutorial for Vora 2.0. Best regards.
