### ISSUE TITLE
Install and Configure unixODBC on HANA Express VM

### ISSUE THREAD

**Issue by Sygyzmundovych** [SAPDocuments/How-Tos#233]
This does not work on HXE VM as there is no repository configured in YaST. Could you add a step to this tutorial which repository to use to install ODBC? Thank you!

**Comment by aplata-sap** [comment]
Hi there,

The repositories are configured once you register your version of SUSE. Registering your version of SUSE is mentioned as a prerequisite. I can make a more prominent note for VM users.

**Comment by JCurrie27** [comment]
How-to updated in latest checkin (pull request #237)
