### ISSUE TITLE
SAP Leonardo Machine Learning and the iOS SDK

### ISSUE THREAD

**Issue by nileshkum** [SAPDocuments/How-Tos#238]
Hi , 
While creating a new project I am getting error "No Such Module Found SAPFoundation", all my Frameworks are added though.

Not sure why I am getting Error.

![error](https://user-images.githubusercontent.com/26800287/33056970-71c81b62-ceae-11e7-87b0-d8f439b9c009.png)

![swift version](https://user-images.githubusercontent.com/26800287/33056956-5c964890-ceae-11e7-97c5-559fdfe0223a.png)

![xcode](https://user-images.githubusercontent.com/26800287/33056937-456da9d8-ceae-11e7-8d53-c6da4e539e4b.png)

1. My XCode version is 9.1(9B55)
2. I have downloaded IOS SDK 2.0 PL02
![sdk](https://user-images.githubusercontent.com/26800287/33056930-365561b6-ceae-11e7-9618-d14a394b99ae.png)

**Comment by qualiture** [comment]
Hi @nileshkum,

Can you check if the framework is also listed under **Embedded Binaries** as well as **Linked Frameworks and Libraries** in the **General** tab of your Xcode project settings?

<img width="666" alt="screen shot 2017-11-23 at 15 15 28" src="https://user-images.githubusercontent.com/7068851/33176951-333b8dca-d061-11e7-8394-754c453932c3.png">

**Comment by thecodester** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
