### ISSUE TITLE
Connect to SAP HANA, express edition using Python

### ISSUE THREAD

**Issue by Paddre** [SAPDocuments/How-Tos#244]
I installed a hdbclient trial which I requested on the linked size and cannot find any hdbcli-X.Y.Z.zip in the respective program folder (C:\Program Files\sap\hdbclient\).
How can I install the python driver then? or is this just not included in the trial?

**Comment by adadouche** [comment]
Hi,

I just updated the content.

You should follow the instructions from the following [How to](https://www.sap.com/developer/how-tos/2016/12/hxe-ua-howto-installing-clients.html) to complete your SAP HANA client installation.

Regards
