### ISSUE TITLE
How to setup SAP HANA, express edition and SAP Vora, developer edition to enable them to connect to each other

### ISSUE THREAD

**Issue by azyubing** [SAPDocuments/How-Tos#249]
Hello,
I found an confusion here.
Document: 
https://www.sap.com/developer/how-tos/2017/04/sda-hana-vora.html
Step 3: Install the SAP HANA Spark controller
For the Configure hanaes-site.xml section, here was my configuration:

    <property>
        <name>sap.hana.es.server.port</name>
        <value>7860</value>
        <final>true</final>
        <description>Port of the host for HANA</description>
    </property>

The description is confusing. It should be "Port number for Spark controller to listen." instead of "Port of the host for HANA", shouldn't it?

**Comment by adadouche** [comment]
Hi,

you are right this should be described as the port used by HANA to communicate with the Spark controller.

This extract is coming form the official documentation:

https://help.sap.com/viewer/6437091bdb1145d9be06aeec79f06363/2.0.2.0/en-US/fcd6d2d26e6c4904a09b7e0c0d4719ba.html

I have submitted your comment using the feedback button ther.

I'll adjust the content in the meantime. (commit  e8eac2e)
