### ISSUE TITLE
Connect to SAP HANA, express edition using JDBC

### ISSUE THREAD

**Issue by lnryan** [SAPDocuments/How-Tos#257]
Can you provide an example of how to provide the credentials through configuration or environment settings rather than hard-coding them in the code. Hard-coded credentials are generally considered bad-practice and only giving this kind of an example in tutorials does not provide a Production-ready alternative.

Thanks alot.

**Comment by Lsubatin** [comment]
The aim of these tutorials is not to provide production-ready alternatives., Once again, this is not the proper forum for support.

There is plenty of SAP and non-SAP documentation on authentication methods depending on the language you will use to embed the JDBC connection and what your input and landscape look like.

**Comment by lnryan** [comment]
@Lsubatin - Tutorials should generally model what _could_ go to production and best practice or point to appropriate resources where they deviate.
