### ISSUE TITLE
Feedback on Tutorial: Connect to HXE using JDBC

### ISSUE THREAD

**Issue by mchytracek** [SAPDocuments/How-Tos#35]
This does not work for me. My HXE VM is up and running as expected, i can connect from the Eclipse Dev Studio, so i think the HXE installation is correct.
I followed the tutorial but cannot connect, always get a 
SAP DBTech JDBC: Cannot connect to jdbc:sap://<myhostname>:30015/ [Cannot connect to host <myhostname>:30015 [Connection refused], -813.].

Regards
Michael

**Comment by luto65** [comment]
I have the same problem, using SAP HANA2 Express.

**Comment by JCurrie27** [comment]
Assigned to Chris.

**Comment by carlsoane** [comment]
Hello @luto65:

The correct default connect string for JDBC with HANA Express 2.0 is: 
jdbc:sap://<ServerName>:39015/?autocommit=false

Please verify that your instance number is 90. 

Note: mchytracek was using HANA Express 1.x for which the default instance number is "00". And, the connect string he posted was missing the server name. Unfortunately, it looks like we did not get back to him back then.

Regards,

Carl
