### ISSUE TITLE
Feedback on Tutorial: How to connect to SAP HANA database server in Python

### ISSUE THREAD

**Issue by sujoy1968** [SAPDocuments/How-Tos#36]
The syntax for connection does not handle multi database container (MCD) HANA configuration. Please advise.

I can connect to HDBSQL using the following command:

hdbsql -u SYSTEM -p  <password> -d SystemDB

However, I am unable to specify the database in the Connect command in Python.

**Comment by scherbinek** [comment]
I was able to connect to the tenant database using the correct SQL port. No need to specify the tenant database.

Please check the ports with the following statement on the tenant database and try connecting with the hostname
SELECT SERVICE_NAME, PORT, SQL_PORT, (PORT + 2) HTTP_PORT FROM SYS.M_SERVICES WHERE ((SERVICE_NAME='indexserver' and COORDINATOR_TYPE= 'MASTER') or (SERVICE_NAME='xsengine'))

Or with the following statement on the SystemDB
SELECT DATABASE_NAME, SERVICE_NAME, PORT, SQL_PORT, (PORT + 2) HTTP_PORT FROM SYS_DATABASES.M_SERVICES WHERE DATABASE_NAME='<DBNAME>' and ((SERVICE_NAME='indexserver' and COORDINATOR_TYPE= 'MASTER') or (SERVICE_NAME='xsengine'))
