### ISSUE TITLE
How to connect to SAP HANA database server in Python

### ISSUE THREAD

**Issue by luto65** [SAPDocuments/How-Tos#58]
My host is a Mac OS X(El Capitan) and the dbapi fails.

Furthermore, I cannot find any port 39015 being available on the hxehost , from the host, when using nmap.

Is that still valid also for SAP HANA2 Express ?

**Comment by JCurrie27** [comment]
Assigning to Chris Huston.

**Comment by carlsoane** [comment]
Hello @luto65:

If you haven't reviewed the How-To, http://www.sap.com/developer/how-tos/2016/08/hxe-python-connection.html, I would recommend doing so.

Here's a snippet of code I used to test a connection to HXE using Python with DBAPI:
#######################################################
import dbapi
#Replace with your hostname, unique port for the database you are connecting,
#UserID and password in that order.
connection=dbapi.connect('hxehost', 39013, 'system', 'MyPassword')
#This statement prints true if the connection is successfully established
print connection.isconnected()
#######################################################

Another option is to use pyhdb. If you have pip, you can install pyhdb with "pip install pyhdb". And then your connection would look like this:
########################################
import pyhdb
connection = pyhdb.connect(
    host='10.173.171.204',
    port='39013',
    user='System',
    password='MyPassword'
)
cursor = connection.cursor()
myStatement = "SELECT * from dummy"
cursor.execute(myStatement)
myResult = cursor.fetchone()
print myResult
########################################

Regards,


Carl
